server:
  port: ${PORT:0}

spring:
  application:
    name: msvc-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/login-example
    username: postgres
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 34872398FHDSFGSFGF78DSF376FSEFDSFGSF423GSDF
  expire: 200000